import numpy as v
import matplotlib.pyplot as plt
f=input('enter the frequency')
fs=input('enter the sample frequency')
n=v.arange(0,10,0.05)
A=v.sin((2*v.pi*n*f)/fs)
B=v.cos((2*v.pi*n*f)/fs)
C=A+A;
D=B+B;
plt.figure(1)
plt.subplot(3,1,1)
plt.plot(n,A)
plt.title("sin wave")
plt.xlabel("----->time")
plt.ylabel("---->amplitude")
plt.subplot(3,1,2)
plt.plot(n,A)
plt.title("sin1 wave")
plt.xlabel("----->time")
plt.ylabel("---->amplitude")
plt.subplot(3,1,3)
plt.plot(n,C)
plt.title("ADDITION OF ABOVE WAVES wave")
plt.xlabel("----->time")
plt.ylabel("---->amplitude")
plt.figure(2)
plt.subplot(3,1,1)
plt.plot(n,B)
plt.title("cos wave")
plt.xlabel("----->time")
plt.ylabel("---->amplitude")
plt.plot(n,B)
plt.subplot(3,1,2)
plt.plot(n,B)
plt.title("cos wave")
plt.xlabel("----->time")
plt.ylabel("---->amplitude")
plt.plot(n,B)
plt.subplot(3,1,3)
plt.plot(n,B)
plt.title("ADDITION OF ABOVE COS WAVES")
plt.xlabel("----->time")
plt.ylabel("---->amplitude")
plt.plot(n,D)
plt.show( )